### ISSUE TITLE
Request to update Pyodide build toolchain version

### ISSUE THREAD

**Issue by ryanking13** [kylebarron/arro3#343]
Hello from [Pyodide](https://github.com/pyodide/pyodide)!

We're opening this issue to request an update to the Pyodide build toolchain version used for the following packages:

* `arro3-io`
* `arro3-compute`
* `arro3-core`

---

## Why this is important

Pyodide has upgraded its build toolchain for packages and the runtime from **(Python 3.12, Emscripten 3.1.58)** to **(Python 3.13, Emscripten 4.0.9)**.

For your packages to be included in the next Pyodide release (planned for June), they must be built with this new toolchain. Otherwise, they will not be available in Pyodide.

---

## Required Changes

To update your build, please make the following changes:

1.  Add this line to your `pyproject.toml`:

    ```toml
    [tool.pyodide.build]
    default_cross_build_env_url = "https://github.com/pyodide/pyodide/releases/download/0.28.0a3/xbuildenv-0.28.0a3.tar.bz2"
    ```

    OR

    Pass the `DEFAULT_CROSS_BUILD_ENV_URL` environment variable when running `pyodide build`:

    ```bash
    DEFAULT_CROSS_BUILD_ENV_URL="https://github.com/pyodide/pyodide/releases/download/0.28.0a3/xbuildenv-0.28.0a3.tar.bz2" pyodide build
    ```

2.  Upgrade the Python version used to build the package against Pyodide to `3.13`.

---

If you encounter any issues after making these changes, please don't hesitate to let us know.

---

## Update the Pyodide Distribution

Once your packages are built with the new toolchain, please create a Pull Request in [pyodide/pyodide-recipes](https://github.com/pyodide/pyodide-recipes) to update the package URLs.
